logging:
  level:
    org:
      springframework:
        web: INFO
        security: INFO
    com:
      shuyun365: DEBUG

endpoints:
  sensitive: false
  shutdown:
    enabled: true


spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/yhj?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
        username: root
        password: 12345678
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        hibernate:
          ddl-auto: create-drop
        show-sql: true

